name: "release Workflow"
description: "create release"

inputs:
  RELEASE_BRANCH: 
    description: "release branch"
    required: true

  GITHUB_TOKEN:
     description: "token"
     required: true

runs:
  using: "composite"
  steps:
      - name: Release
        uses: K-Phoen/semver-release-action@master
        with:
         release_branch: ${{ inputs.RELEASE_BRANCH }}
        env:
          GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
